//list of street names in tampere from http://www.puhdistussuunnitelmat.fi/tampere/kadut.htm
//here are only the ones with 'ä', 'ö' or 'å' in them

module.exports = {
    "Erkkilankatu": "Erkkilänkatu",
    "Eratie": "Erätie",
    "Etelapuisto": "Eteläpuisto",
    "F.E. Sillanpaan katu": "F.E. Sillanpään katu",
    "Hakametsankatu": "Hakametsänkatu",
    "Hatanpaan valtatie": "Hatanpään valtatie",
    "Hatanpaankatu": "Hatanpäänkatu",
    "Heinatori": "Heinätori",
    "Hervannan valtavayla": "Hervannan valtaväylä",
    "Huhtimaenkatu": "Huhtimäenkatu",
    "Hyypanpolku": "Hyypänpolku",
    "Hakilapolku": "Häkiläpolku",
    "Hallapyorankatu": "Hälläpyöränkatu",
    "Hameenkatu": "Hämeenkatu",
    "Hameenpuisto": "Hämeenpuisto",
    "Hoyrypuusepanpolku": "Höyrypuusepänpolku",
    "Ilomaentie": "Ilomäentie",
    "Ilvestie": "Ilvestie",
    "Itsenaisyydenkatu": "Itsenäisyydenkatu",
    "Itainenkatu": "Itäinenkatu",
    "Juhannuskylankatu": "Juhannuskylänkatu",
    "Jarvensivuntie": "Järvensivuntie",
    "Jaahallinraitti": "Jäähallinraitti",
    "Kehrasaari": "Kehräsaari",
    "Keihaskatu": "Keihäskatu",
    "Kenttakatu": "Kenttäkatu",
    "Kisakentankatu": "Kisakentänkatu",
    "Kyrolankatu": "Kyrölänkatu",
    "Kyttalankatu": "Kyttälänkatu",
    "Kaenkuja": "Käenkuja",
    "Karpankatu": "Kärpänkatu",
    "Karkikuja": "Kärkikuja",
    "Kaatykatu": "Käätykatu",
    "Lemminkaisenkatu": "Lemminkäisenkatu",
    "Lempaalantie": "Lempääläntie",
    "Leppakatu": "Leppäkatu",
    "Lahteenkatu": "Lähteenkatu",
    "Laakarinkatu": "Lääkärinkatu",
    "Makipaankatu": "Mäkipäänkatu",
    "Mantykatu": "Mäntykatu",
    "Mataspera": "Mätäsperä",
    "Nakotornintie": "Näkötornintie",
    "Narhinpolku": "Närhinpolku",
    "Nasijarvenkatu": "Näsijärvenkatu",
    "Nasilinnankatu": "Näsilinnankatu",
    "Naadankatu": "Näädänkatu",
    "Palomaentie": "Palomäentie",
    "Pyhajarvenkatu": "Pyhäjärvenkatu",
    "Pyharanta": "Pyhäranta",
    "Paaskynpolku": "Pääskynpolku",
    "Pollontaival": "Pöllöntaival",
    "Rievakatu": "Rieväkatu",
    "Sahanterankatu": "Sahanteränkatu",
    "Sepankatu": "Sepänkatu",
    "Sarkanniemi": "Särkänniemi",
    "Torngrenin aukio": "Törngrenin aukio",
    "Toyrytie": "Töyrytie",
    "Uudenkylankatu": "Uudenkylänkatu",
    "Uudenkylankuja": "Uudenkylänkuja",
    "Vainamoisenkatu": "Väinämöisenkatu",
    "Vainamoisenkuja": "Väinämöisenkuja",
    "Vaino Linnan aukio": "Väinö Linnan aukio",
    "Vainolankatu": "Väinölänkatu",
    "Valimaankatu": "Välimaankatu",
    "Valisola": "Välisola",
    "Varjarinkuja": "Värjärinkuja",
    "Yrjonkatu": "Yrjönkatu",
    "Akerlundinkatu": "Åkerlundinkatu",
}
